### ISSUE TITLE
Be able to export dataset values

### ISSUE THREAD

**Issue by yu-smc** [t29mato/starry-digitizer#86]
Export the data required for replicating the Digitizer's drawing in JSON format.

## Conditions to start this work
- Resolve related issues in the following order, then start the implementation of export feature
  - [x] [Separate domains and applications](https://github.com/t29mato/starry-digitizer/issues/83)
  - [x] [Add domain repository](https://github.com/t29mato/starry-digitizer/issues/100)
  - [x] [Discontinuation of Pinia](https://github.com/t29mato/starry-digitizer/issues/71)
